# Generated by Django 3.0.3 on 2020-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('activity', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('about_event', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_mem', models.ImageField(upload_to='')),
                ('name_member', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_so', models.ImageField(upload_to='')),
                ('name_so', models.CharField(max_length=120)),
                ('discription', models.TextField(max_length=145)),
            ],
        ),
        migrations.CreateModel(
            name='xtreme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('team', models.IntegerField()),
            ],
        ),
    ]
