# Generated by Django 3.0.3 on 2020-04-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('activity', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('about_event', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_mem', models.ImageField(upload_to='static/persons')),
                ('name_member', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('society_mem', models.CharField(default='IEEE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_so', models.ImageField(upload_to='static/images')),
                ('name_so', models.CharField(max_length=120)),
                ('discription', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Xtreme',
            fields=[
                ('version', models.IntegerField(default=9, primary_key=True, serialize=False)),
                ('team_no', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('global_rank', models.IntegerField(default=1)),
                ('region_rank', models.IntegerField(default=1)),
                ('country_rank', models.IntegerField(default=1)),
                ('college_rank', models.IntegerField(default=1)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Xtreme')),
            ],
        ),
    ]
