# Generated by Django 3.0.3 on 2020-03-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtreme',
            name='team',
        ),
        migrations.AlterField(
            model_name='member',
            name='image_mem',
            field=models.ImageField(upload_to='static/persons'),
        ),
        migrations.AlterField(
            model_name='society',
            name='image_so',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Xtreme')),
            ],
        ),
    ]
