# Generated by Django 3.0.3 on 2020-06-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='about_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='coverImage',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='detailTxt',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='detailUrl',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='eventid',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_mem',
            field=models.ImageField(upload_to='static/media/persons'),
        ),
        migrations.AlterField(
            model_name='society',
            name='image_so',
            field=models.ImageField(upload_to='static/media/images'),
        ),
    ]
