# Generated by Django 3.0.3 on 2020-03-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='version',
        ),
    ]
