# Generated by Django 3.0.3 on 2020-03-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20200326_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtreme',
            name='team_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Xtreme'),
        ),
        migrations.AlterField(
            model_name='xtreme',
            name='version',
            field=models.IntegerField(default=9),
        ),
    ]
