# Generated by Django 3.0.3 on 2020-03-30 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_remove_team_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='version',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='section.Xtreme'),
        ),
    ]
