# Generated by Django 3.0.3 on 2020-06-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20200626_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
