# Generated by Django 3.0.3 on 2020-03-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_team_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
