# Generated by Django 3.0.3 on 2020-06-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_remove_event_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
