# Generated by Django 3.0.3 on 2020-03-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('global_rank', models.IntegerField(default=1)),
                ('region_rank', models.IntegerField(default=1)),
                ('country_rank', models.IntegerField(default=1)),
                ('college_rank', models.IntegerField(default=1)),
                ('version', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='section.Xtreme')),
            ],
        ),
    ]
