# Generated by Django 3.0.3 on 2020-04-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='version',
            field=models.IntegerField(default=9),
        ),
    ]
