# Generated by Django 3.0.3 on 2020-04-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_auto_20200403_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Xtreme'),
        ),
    ]
