# Generated by Django 3.0.3 on 2020-03-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_auto_20200326_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='college_rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='country_rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='global_rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='region_rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Xtreme'),
        ),
    ]
