# Generated by Django 3.0.3 on 2020-03-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0008_auto_20200326_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='society_mem',
            field=models.CharField(default='IEEE', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Xtreme'),
        ),
    ]
