# Generated by Django 3.0.3 on 2020-03-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0009_auto_20200327_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='discription',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Xtreme'),
        ),
    ]
